rizza_calendar_event_list:
  pattern:  /
  defaults: { _controller: RizzaCalendarBundle:Event:list }

rizza_calendar_event_show:
  pattern:  /show/{id}
  defaults: { _controller: RizzaCalendarBundle:Event:show }

rizza_calendar_event_add:
  pattern:  /add
  defaults: { _controller: RizzaCalendarBundle:Event:add }

rizza_calendar_event_edit:
  pattern:  /edit/{id}
  defaults: { _controller: RizzaCalendarBundle:Event:edit }

rizza_calendar_event_delete:
  pattern: /delete/{id}
  defaults: { _controller: RizzaCalendarBundle:Event:delete }
